# -*- coding: utf-8 -*-

"""
sampleapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from sampleapi.api_helper import APIHelper


class APIControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(APIControllerTests, cls).setUpClass()
        cls.controller = cls.client.client
        cls.response_catcher = cls.controller.http_call_back

    # Get a list of items
    def test_get_a_list_of_items(self):

        # Perform the API call through the SDK function
        result = self.controller.get_a_list_of_items()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


