# -*- coding: utf-8 -*-

"""
sampleapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from sampleapi.api_helper import APIHelper
from sampleapi.models.item import Item


class ItemsResponse(object):

    """Implementation of the 'Items Response' model.

    Attributes:
        items (List[Item]): The model property of type List[Item].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "items": 'items'
    }

    _optionals = [
        'items',
    ]

    def __init__(self,
                 items=APIHelper.SKIP):
        """Constructor for the ItemsResponse class"""

        # Initialize members of the class
        if items is not APIHelper.SKIP:
            self.items = items 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        items = None
        if dictionary.get('items') is not None:
            items = [Item.from_dictionary(x) for x in dictionary.get('items')]
        else:
            items = APIHelper.SKIP
        # Return an object of this model
        return cls(items)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'items={(self.items if hasattr(self, "items") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'items={(self.items if hasattr(self, "items") else None)!s})')
