# -*- coding: utf-8 -*-

"""
sampleapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from sampleapi.api_helper import APIHelper


class Specifications(object):

    """Implementation of the 'Specifications' model.

    Attributes:
        weight (float): The model property of type float.
        dimensions (str): The model property of type str.
        material (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "weight": 'weight',
        "dimensions": 'dimensions',
        "material": 'material'
    }

    _optionals = [
        'weight',
        'dimensions',
        'material',
    ]

    def __init__(self,
                 weight=APIHelper.SKIP,
                 dimensions=APIHelper.SKIP,
                 material=APIHelper.SKIP):
        """Constructor for the Specifications class"""

        # Initialize members of the class
        if weight is not APIHelper.SKIP:
            self.weight = weight 
        if dimensions is not APIHelper.SKIP:
            self.dimensions = dimensions 
        if material is not APIHelper.SKIP:
            self.material = material 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        weight = dictionary.get("weight") if dictionary.get("weight") else APIHelper.SKIP
        dimensions = dictionary.get("dimensions") if dictionary.get("dimensions") else APIHelper.SKIP
        material = dictionary.get("material") if dictionary.get("material") else APIHelper.SKIP
        # Return an object of this model
        return cls(weight,
                   dimensions,
                   material)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'weight={(self.weight if hasattr(self, "weight") else None)!r}, '
                f'dimensions={(self.dimensions if hasattr(self, "dimensions") else None)!r}, '
                f'material={(self.material if hasattr(self, "material") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'weight={(self.weight if hasattr(self, "weight") else None)!s}, '
                f'dimensions={(self.dimensions if hasattr(self, "dimensions") else None)!s}, '
                f'material={(self.material if hasattr(self, "material") else None)!s})')
