# -*- coding: utf-8 -*-

"""
sampleapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEnum(object):

    """Implementation of the 'Status' enum.

    Attributes:
        ACTIVE: The enum member of type str.
        INACTIVE: The enum member of type str.
        PENDING: The enum member of type str.

    """
    _all_values = ['active', 'inactive', 'pending']
    ACTIVE = 'active'

    INACTIVE = 'inactive'

    PENDING = 'pending'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   